services:
  websocket:
    container_name: iot-monitor
    build: ./iot-app
    volumes:
      - ~/certs:/certs
    ports:
      - 8000:8000

  angular:
    container_name: iot-angular
    build: ./angular-bld
    volumes:
      - ~/certs:/etc/ssl/certs
    ports:
      - 80:8080
      - 443:4443

  ollama:
    container_name: iot-ollama
    image: ollama/ollama:latest
    volumes:
      - ./data/ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=http://*
    ports: 
      - 11434:11434

networks:
  default:
    name: tulip-net
    external: true
