name: mini workflow

on:
  workflow_dispatch:
    inputs:
      IsProd:
          type: boolean
          required: true      
          
jobs:
  do-thing:
    runs-on: ubuntu-latest
    steps:
    - name: Step 1
      run: |
        VERSION_CODE=1
        echo "VERSION_CODE=$VERSION_CODE" >> ./test

    - name: view versionCode
      run: cat ./test
    
    - name: Step 3
      run: |
        if [ ${{ inputs.IsProd }} ]; then
          VERSION_CODE=$((${{ github.run_number }} + ${{ env.VERSION_CODE }}))
          echo "VERSION_CODE=$VERSION_CODE" >> ./test
        fi

    - name: view versionCode
      run: cat ./test
      
  
